name: build

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Setup vcpkg
        shell: powershell
        run: |
          if (-not (Test-Path "vcpkg")) {
            git clone https://github.com/microsoft/vcpkg
            .\vcpkg\bootstrap-vcpkg.bat
          }

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            vcpkg
            vcpkg\installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Install dependencies
        shell: powershell
        run: .\vcpkg\vcpkg install sdl2 sdl2-image glew --triplet x64-windows-static
    
      - name: List vcpkg libraries
        shell: powershell
        run: |
          $vcpkgLibDir  = ".\vcpkg\installed\x64-windows-static\lib"
          Write-Host "=== Listing all .lib files in $vcpkgLibDir ==="
          Get-ChildItem $vcpkgLibDir\*.lib | ForEach-Object { Write-Host $_.Name }

      - name: Build
        shell: powershell
        run: |
          $vcpkgLibDir = ".\vcpkg\installed\x64-windows-static\lib"

          $vcpkgLibs = Get-ChildItem $vcpkgLibDir\*.lib |
                  Where-Object { $_.Name -notmatch "d\.lib$" } |
                  ForEach-Object { $_.FullName }

          $systemLibs = @(
              "user32.lib",
              "gdi32.lib",
              "shell32.lib",
              "ole32.lib",
              "oleaut32.lib",
              "advapi32.lib",
              "winmm.lib",
              "imm32.lib",
              "version.lib",
              "propsys.lib",
              "setupapi.lib",
              "cfgmgr32.lib",
              "comdlg32.lib",
              "shlwapi.lib",
              "hid.lib",
              "opengl32.lib",
              "dinput8.lib",
              "dxguid.lib",
              "uuid.lib"
          )

          $allLibs = $vcpkgLibs + $systemLibs

          cl /O2 /MT main.c /I ".\vcpkg\installed\x64-windows-static\include" /D GLEW_STATIC /D SDL_MAIN_HANDLED /link $($allLibs -join ' ') /OUT:demo-windows.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: demo-windows.exe